create database msql01;

create table if not exists e1 (
    e1_id int primary key not null
);

create table if not exists e2 (
    e2_id int primary key not null
);

create table if not exists e3 (
    e3_id int primary key not null
);

create table if not exists e4 (
    e4_id int primary key not null
);

-- Generated by MDot
