create database msql01;

create table if not exists e1 (
    e1_id int primary key not null
);

create table if not exists e2 (
    e2_id int primary key not null
);

create table if not exists e3 (
    e3_id int primary key not null,
    e5 int not null
);

create table if not exists e4 (
    e4_id int primary key not null
);

create table if not exists e5 (
    e5_id int primary key not null,
    e3 int
);

create table if not exists l1 (
    e3 int not null,
    e4 int not null
);

create table if not exists l2 (
    e2 int not null,
    e4 int not null
);

alter table l1 add constraint fk_lk_l1_e3
    foreign key(e3)
    references e3.e3_id;

alter table l1 add constraint fk_lk_l1_e4
    foreign key(e4)
    references e4.e4_id;

alter table l2 add constraint fk_lk_l2_e2
    foreign key(e2)
    references e2.e2_id;

alter table l2 add constraint fk_lk_l2_e4
    foreign key(e4)
    references e4.e4_id;

alter table e3 add constraint fk_e3_e5
    foreign key(e5)
    references e5.e5_id;

alter table e5 add constraint fk_e5_e3
    foreign key(e3)
    references e3.e3_id;

-- Generated by MDot
