create database msql02;

create table if not exists e1 (
    e1_id int primary key not null,
    e3 int not null
);

create table if not exists e2 (
    e2_id int primary key not null
);

create table if not exists e3 (
    e3_id int primary key not null
);

alter table e1 add constraint lk_e1_e3
    foreign key(e3) references e3.e3_id;

-- Generated by MDot
